version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: darkside-development-customer-management
    container_name: darkside-development-customer-management
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - ./:/var/www
      - /var/www/vendor
      - /var/www/node_modules
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: aml_dark_development
      DB_USERNAME: user
      DB_PASSWORD: password
    networks:
      - laravel
    command: >
       /bin/sh -c "/wait-for-db.sh db &&
              composer install &&
              cp .env.example .env &&
              php artisan migrate --seed &&
              php artisan key:generate &&
              php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: aml_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: aml_dark_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:
    driver: local

networks:
  laravel:
    driver: bridge

