<?php

return [
    'CUSTOMER_FIRST_NAME_MAX_LENGTH' => 100,
    'CUSTOMER_LAST_NAME_MAX_LENGTH' => 100,
    'CUSTOMER_EMAIL_MAX_LENGTH' => 255,
    'CUSTOMER_PHONE_MAX_LENGTH' => 13,
    'CUSTOMER_ADDRESS_MAX_LENGTH' => 2500,
];
